### ISSUE TITLE
behat configuration for local environment

### ISSUE THREAD

**Issue by robinstraub** [Victoire/victoire#950]
## Description
On 2.3 branch I am unable to run behat tests. Commenting [https://github.com/Victoire/victoire/blob/2.3/behat.yml.dist#L16](https://github.com/Victoire/victoire/blob/2.3/behat.yml.dist#L16) helped me getting rid of error `Class 'PHP_CodeCoverage_Filter' not found` but now I get the error `Property Victoire\Bundle\CoreBundle\Entity\EntityProxy::$article does not exist (ReflectionException)`

## Resolution Ideas
A part in the documentation to help to setup a test environment would be very useful.

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |          | Page           |          |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           | &#10004; | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |
| UI             |          |                |          |

**Comment by alexislefebvre** [comment]
About the error, the line that contain `CoverageContext` has to been removed from `behat.yml` and `behat.yml.dist`.

The list of commands required in order to launch tests is written in several places: https://github.com/Victoire/test-suite/blob/1de04929f014ca31144daefbb36d229157458f59/dependencies.sh https://github.com/Victoire/victoire/blob/2b60e4832fc2342f984113f35646adfe9ba66e78/.docker/php-fpm/build.sh https://github.com/Victoire/victoire/blob/2b60e4832fc2342f984113f35646adfe9ba66e78/Tests/test.sh

It would be nice to avoid this duplication of code, and to add a note about this in the documentation.
